server {
    listen 80;
    server_name _;

    # Redireciona para o container 'frontend-react' (porta interna 80)
    location / {
        proxy_pass http://frontend-react:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redireciona para o container 'backend-fastapi' (porta interna 8000)
    location /api/ {
        proxy_pass http://backend-fastapi:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}