server {
    listen 80;
    server_name _;

    # Resolver DNS do Docker (evita o crash do Nginx se um container estiver offline)
    resolver 127.0.0.11 valid=30s;

    # 1. RAIZ (/): Exibe mensagem padrão confirmando que o Nginx está online
    location / {
        default_type text/html;
        return 200 '<html><body><h1>Nginx Reverse Proxy On-line!</h1><p>Status: Operacional na rede lab-net.</p></body></html>';
    }

    # 2. FRONTEND REACT: Acessível via /app/
    location /app/ {
        set $target_react http://frontend-react:80;
        proxy_pass $target_react/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. BACKEND FASTAPI: Acessível via /api/
    location /api/ {
        set $target_fastapi http://backend-fastapi:8000;
        proxy_pass $target_fastapi/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}